[versions]
# Minecraft platforms
paperApi = "1.21.4-R0.1-SNAPSHOT"
velocityApi = "3.4.0-SNAPSHOT"
bungeeApi = "1.21-R0.4"

# Core dependencies
luckperms = "5.5"
configlibYaml = "4.6.3"
gson = "2.13.2"
protobuf = "4.33.0"

# Cloud Commands
cloud = "2.0.0"
cloudMinecraft = "2.0.0-beta.13"
cloudTranslations = "1.0.0-SNAPSHOT"

# Kyori Adventure
adventureApi = "4.25.0"
adventureTextSerializerLegacy = "4.25.0"
adventurePlatformBukkit = "4.4.1"
adventurePlatformBungeecord = "4.4.1"

# Platform specific
paperlib = "1.0.8"
bstatsBukkit = "3.1.0"
bstatsVelocity = "3.1.0"
bstatsBungeecord = "3.1.0"
foliaLib = "0.5.1"

# Testing
apiguardian = "1.1.2"

# Build tools
shadowPlugin = "9.2.2"
spotlessPlugin = "8.0.0"
spotbugsPlugin = "6.4.5"
indraGit = "4.0.0"
jvmdowngrader = "1.3.4"
errorpronePlugin = "4.3.0"
lombokPlugin = "9.1.0"
protobufPlugin = "0.9.5"

# Gradle plugins
foojayResolver = "1.0.0"
runPaper = "3.0.2"
runVelocity = "3.0.2"

[libraries]
# Core dependencies
luckperms-api = { module = "net.luckperms:api", version.ref = "luckperms" }
configlib-yaml = { module = "de.exlll:configlib-yaml", version.ref = "configlibYaml" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }

# Cloud Commands
cloud-core = { module = "org.incendo:cloud-core", version.ref = "cloud" }
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud" }
cloud-brigadier = { module = "org.incendo:cloud-brigadier", version.ref = "cloudMinecraft" }
cloud-translations-core = { module = "org.incendo:cloud-translations-core", version.ref = "cloudTranslations" }
cloud-minecraft-extras = { module = "org.incendo:cloud-minecraft-extras", version.ref = "cloudMinecraft" }
cloud-translations-minecraft-extras = { module = "org.incendo:cloud-translations-minecraft-extras", version.ref = "cloudTranslations" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloudMinecraft" }
cloud-velocity = { module = "org.incendo:cloud-velocity", version.ref = "cloudMinecraft" }
cloud-bungee = { module = "org.incendo:cloud-bungee", version.ref = "cloudMinecraft" }

# Kyori Adventure
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventureApi" }
adventure-text-serializer-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventureTextSerializerLegacy" }
adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventurePlatformBukkit" }
adventure-platform-bungeecord = { module = "net.kyori:adventure-platform-bungeecord", version.ref = "adventurePlatformBungeecord" }

# Platform specific
paperlib = { module = "io.papermc:paperlib", version.ref = "paperlib" }
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstatsBukkit" }
bstats-velocity = { module = "org.bstats:bstats-velocity", version.ref = "bstatsVelocity" }
bstats-bungeecord = { module = "org.bstats:bstats-bungeecord", version.ref = "bstatsBungeecord" }
folia-lib = { module = "com.tcoded:FoliaLib", version.ref = "foliaLib" }

# Minecraft platforms
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paperApi" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocityApi" }
bungeecord-api = { module = "net.md-5:bungeecord-api", version.ref = "bungeeApi" }

# Testing
apiguardian-api = { module = "org.apiguardian:apiguardian-api", version.ref = "apiguardian" }

# Build tools
shadow-gradle-plugin = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadowPlugin" }
spotless-plugin-gradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotlessPlugin" }
spotbugs-gradle-plugin = { module = "com.github.spotbugs.snom:spotbugs-gradle-plugin", version.ref = "spotbugsPlugin" }
indra-git = { module = "net.kyori:indra-git", version.ref = "indraGit" }
jvmdowngrader-gradle-plugin = { module = "xyz.wagyourtail.jvmdowngrader:xyz.wagyourtail.jvmdowngrader.gradle.plugin", version.ref = "jvmdowngrader" }
errorprone-gradle-plugin = { module = "net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin", version.ref = "errorpronePlugin" }
lombok-gradle-plugin = { module = "io.freefair.gradle:lombok-plugin", version.ref = "lombokPlugin" }

[plugins]
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojayResolver" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
run-velocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runVelocity" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
